// Mocks generated by Mockito 5.4.6 from annotations
// in products_app/test/mocks/generate_mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:products_app/data/data_sources/local/favorites/favorites_local_data_source.dart'
    as _i5;
import 'package:products_app/data/data_sources/remote/products/apis/products_remote_data_source.dart'
    as _i3;
import 'package:products_app/data/data_sources/remote/products/models/product_response.dart'
    as _i2;
import 'package:products_app/data/data_sources/remote/products/models/review_response.dart'
    as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeProductsResponse_0 extends _i1.SmartFake
    implements _i2.ProductsResponse {
  _FakeProductsResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ProductsRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductsRemoteDataSource extends _i1.Mock
    implements _i3.ProductsRemoteDataSource {
  MockProductsRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.ProductsResponse> getProducts() =>
      (super.noSuchMethod(
            Invocation.method(#getProducts, []),
            returnValue: _i4.Future<_i2.ProductsResponse>.value(
              _FakeProductsResponse_0(
                this,
                Invocation.method(#getProducts, []),
              ),
            ),
          )
          as _i4.Future<_i2.ProductsResponse>);
}

/// A class which mocks [FavoritesLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockFavoritesLocalDataSource extends _i1.Mock
    implements _i5.FavoritesLocalDataSource {
  MockFavoritesLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<Set<int>> getFavorites() =>
      (super.noSuchMethod(
            Invocation.method(#getFavorites, []),
            returnValue: _i4.Future<Set<int>>.value(<int>{}),
          )
          as _i4.Future<Set<int>>);

  @override
  _i4.Future<void> saveFavorites(Set<int>? ids) =>
      (super.noSuchMethod(
            Invocation.method(#saveFavorites, [ids]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [ProductsResponse].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductsResponse extends _i1.Mock implements _i2.ProductsResponse {
  @override
  set products(List<_i2.ProductResponse>? value) => super.noSuchMethod(
    Invocation.setter(#products, value),
    returnValueForMissingStub: null,
  );

  @override
  set total(int? value) => super.noSuchMethod(
    Invocation.setter(#total, value),
    returnValueForMissingStub: null,
  );

  @override
  set skip(int? value) => super.noSuchMethod(
    Invocation.setter(#skip, value),
    returnValueForMissingStub: null,
  );

  @override
  set limit(int? value) => super.noSuchMethod(
    Invocation.setter(#limit, value),
    returnValueForMissingStub: null,
  );

  @override
  Map<String, dynamic> toJson() =>
      (super.noSuchMethod(
            Invocation.method(#toJson, []),
            returnValue: <String, dynamic>{},
            returnValueForMissingStub: <String, dynamic>{},
          )
          as Map<String, dynamic>);
}

/// A class which mocks [ProductResponse].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductResponse extends _i1.Mock implements _i2.ProductResponse {
  @override
  set id(int? value) => super.noSuchMethod(
    Invocation.setter(#id, value),
    returnValueForMissingStub: null,
  );

  @override
  set title(String? value) => super.noSuchMethod(
    Invocation.setter(#title, value),
    returnValueForMissingStub: null,
  );

  @override
  set description(String? value) => super.noSuchMethod(
    Invocation.setter(#description, value),
    returnValueForMissingStub: null,
  );

  @override
  set category(String? value) => super.noSuchMethod(
    Invocation.setter(#category, value),
    returnValueForMissingStub: null,
  );

  @override
  set price(double? value) => super.noSuchMethod(
    Invocation.setter(#price, value),
    returnValueForMissingStub: null,
  );

  @override
  set discountPercentage(double? value) => super.noSuchMethod(
    Invocation.setter(#discountPercentage, value),
    returnValueForMissingStub: null,
  );

  @override
  set rating(double? value) => super.noSuchMethod(
    Invocation.setter(#rating, value),
    returnValueForMissingStub: null,
  );

  @override
  set stock(int? value) => super.noSuchMethod(
    Invocation.setter(#stock, value),
    returnValueForMissingStub: null,
  );

  @override
  set tags(List<String>? value) => super.noSuchMethod(
    Invocation.setter(#tags, value),
    returnValueForMissingStub: null,
  );

  @override
  set brand(String? value) => super.noSuchMethod(
    Invocation.setter(#brand, value),
    returnValueForMissingStub: null,
  );

  @override
  set sku(String? value) => super.noSuchMethod(
    Invocation.setter(#sku, value),
    returnValueForMissingStub: null,
  );

  @override
  set weight(int? value) => super.noSuchMethod(
    Invocation.setter(#weight, value),
    returnValueForMissingStub: null,
  );

  @override
  set warrantyInformation(String? value) => super.noSuchMethod(
    Invocation.setter(#warrantyInformation, value),
    returnValueForMissingStub: null,
  );

  @override
  set shippingInformation(String? value) => super.noSuchMethod(
    Invocation.setter(#shippingInformation, value),
    returnValueForMissingStub: null,
  );

  @override
  set availabilityStatus(String? value) => super.noSuchMethod(
    Invocation.setter(#availabilityStatus, value),
    returnValueForMissingStub: null,
  );

  @override
  set reviews(List<_i6.ReviewResponse>? value) => super.noSuchMethod(
    Invocation.setter(#reviews, value),
    returnValueForMissingStub: null,
  );

  @override
  set returnPolicy(String? value) => super.noSuchMethod(
    Invocation.setter(#returnPolicy, value),
    returnValueForMissingStub: null,
  );

  @override
  set minimumOrderQuantity(int? value) => super.noSuchMethod(
    Invocation.setter(#minimumOrderQuantity, value),
    returnValueForMissingStub: null,
  );

  @override
  set images(List<String>? value) => super.noSuchMethod(
    Invocation.setter(#images, value),
    returnValueForMissingStub: null,
  );

  @override
  set thumbnail(String? value) => super.noSuchMethod(
    Invocation.setter(#thumbnail, value),
    returnValueForMissingStub: null,
  );

  @override
  Map<String, dynamic> toJson() =>
      (super.noSuchMethod(
            Invocation.method(#toJson, []),
            returnValue: <String, dynamic>{},
            returnValueForMissingStub: <String, dynamic>{},
          )
          as Map<String, dynamic>);
}
